services:
  - type: web
    name: romantic-countdown-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 