services:
  - type: web
    name: romantic-countdown-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build:server
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 